create table if not exists endpoint_hits
(
    id   bigint generated by default as identity not null,
    uri  varchar(300)                            not null,
    app  varchar(300)                            not null,
    ip   varchar(30)                             not null,
    time timestamp without time zone             not null,
    primary key (id)
);