create table if not exists users
(
    id    bigint generated by default as identity not null,
    email varchar(254)                            not null,
    name  varchar(32)                             not null,
    primary key (id),
    constraint users_unique_email unique (email)
);

create table if not exists category
(
    id   bigint generated by default as identity not null,
    name varchar(32)                             not null,
    primary key (id),
    constraint category_unique_name unique (name)
);

create table if not exists compilation
(
    id     bigint generated by default as identity not null,
    pinned boolean                                 not null,
    title  varchar(128)                            not null,
    primary key (id),
    constraint compilation_unique_title unique (title)
);

create table if not exists event
(
    id                 bigint generated by default as identity not null,
    annotation         varchar(7000)                           not null,
    created_on         timestamp without time zone             not null,
    description        varchar(7000)                           not null,
    event_date         timestamp without time zone             not null,
    lat                float                                   not null,
    lon                float                                   not null,
    paid               boolean                                 not null,
    participant_limit  integer                                 not null,
    published_on       timestamp without time zone,
    confirmed_requests integer,
    request_moderation boolean                                 not null,
    state              varchar(20)                             not null,
    title              varchar(128)                            not null,
    category_id        bigint                                  not null,
    initiator_id       bigint                                  not null,
    primary key (id),
    constraint event_fk_category_id foreign key (category_id) references category,
    constraint event_fk_initiator_id foreign key (initiator_id) references users
);

create table if not exists compilation_events
(
    compilation_id bigint not null,
    events_id      bigint not null,
    primary key (compilation_id, events_id),
    constraint compilation_events_unique_events_id unique (events_id),
    constraint compilation_events_fk_events_id foreign key (events_id) references event,
    constraint compilation_events_fk_compilation_id foreign key (compilation_id) references compilation
);

create table if not exists request
(
    id           bigint generated by default as identity not null,
    created      timestamp without time zone             not null,
    state        varchar(20)                             not null,
    event_id     bigint                                  not null,
    requester_id bigint                                  not null,
    primary key (id),
    constraint request_unique_event_id_requester_id unique (event_id, requester_id),
    constraint request_fk_event_id foreign key (event_id) references event,
    constraint request_fk_requester_id foreign key (requester_id) references users
);

create table if not exists comment
(
    id         bigint generated by default as identity not null,
    event      bigint       not null,
    author     bigint       not null,
    created    timestamp without time zone  not null,
    edited     timestamp without time zone,
    text       varchar(300) not null,
    primary key (id),
    constraint fk_comments_event FOREIGN KEY (event) REFERENCES event (id),
    constraint fk_comments_author FOREIGN KEY (author) REFERENCES users (id)
);

